site_name: gns3fy-next
site_url: https://yueguobin.github.io/gns3fy-next/
site_description: GNS3 REST API python library with API v3 support.
site_author: Guobin Yue
repo_url: https://github.com/yueguobin/gns3fy-next/
repo_name: yueguobin/gns3fy-next
docs_dir: "docs/content/"
theme:
  name: material
  favicon: https://fontawesome.com/icons/stream?style=solid
  icon:
    logo: fontawesome/solid/server
    repo: fontawesome/brands/github
  font:
    text: Nunito
    code: Source Code Pro
  palette:
    scheme: slate
    primary: light blue
    accent: blue grey
  features:
    # - navigation.tabs
    - toc.autohide

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 2-4
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition

extra:

nav:
  - Overview: index.md
  - User Guide: user-guide.md
  - API Reference: api_reference.md
  - About:
    - Release Notes: about/changelog.md
    - License: about/license.md

copyright: 'Copyright &copy; 2025 Guobin Yue'
