[tool.poetry]
name = "gns3fy"
version = "0.7.2"
description = "Python wrapper around GNS3 Server API"
authors = ["David Flores <davidflores7_8@hotmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/davidban77/gns3fy"
homepage = "https://github.com/davidban77/gns3fy"
keywords = ["network", "gns3", "python", "restapi", "netdev"]
classifiers = [
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.22"
pydantic = "^1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
flake8 = "^6.0"
requests-mock = "^1.6"
pytest-cov = "^4.0"
coverage = "^7.0"
black = "^23.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.0"
pydoc-markdown = "*"
mkdocs-material = "^6.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
